### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kulzz** [X606/SpaceWarp#10]
After patching, when starting new save or loading from flight to KSC game will crash. With mods or witouh - all the same
[ LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[LagRemover] [Info] Loaded JOINT_RIGIDITY with value of1500000
[General] [State] Swapping game state! prev: [FlightView] --> new: [Loading]
[Debug] Loading Local Space Kerbin...
[Debug] Kerbin - Local-Space Load Finished. 1.8256s
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: failed to create buffer (target 0x5 mode 0 size 480) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 60) [0x887A0005]
d3d11: failed to create 2D texture id=5589 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5591 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5593 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5537 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 4800) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 768) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5539 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5595 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5541 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5543 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5545 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 4576) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 324) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5547 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5549 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 1320) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 168) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 5120) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 672) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 6760) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 900) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 14080) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 2112) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5551 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5553 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5597 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5555 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 20608) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 3336) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5557 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5559 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 961520) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 116838) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5561 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5563 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5565 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 187328) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 32160) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 3328) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 396) [0x887A0005]
d3d11: failed to create 2D texture id=5599 width=8 height=8 mips=4 dxgifmt=71 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5567 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 1056) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 144) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5569 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5571 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5573 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5575 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5577 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 25920) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 4632) [0x887A0005]
d3d11: failed to create 2D texture shader resource view id=5579 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 104600) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 12120) [0x887A0005]
d3d11: failed to create 2D texture id=5601 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5581 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5583 [D3D error was 887a0005]
d3d11: failed to create 2D texture shader resource view id=5585 [D3D error was 887a0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 15232) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 2832) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 5120) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 672) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 53020) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 4248) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 71856) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 8844) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 649296) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 155850) [0x887A0005]
d3d11: failed to create buffer (target 0x1 mode 0 size 5120) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 672) [0x887A0005]
d3d11: failed to create 2D texture id=5603 width=8 height=8 mips=4 dxgifmt=78 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5605 width=8 height=8 mips=4 dxgifmt=71 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5607 width=32 height=8 mips=6 dxgifmt=78 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5609 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5611 width=8 height=8 mips=4 dxgifmt=78 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5613 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5615 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]
d3d11: failed to create buffer (target 0x5 mode 0 size 480) [0x887A0005]
d3d11: failed to create buffer (target 0x2 mode 0 size 60) [0x887A0005]
d3d11: failed to create 2D texture id=5617 width=8 height=8 mips=4 dxgifmt=71 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5619 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5621 width=8 height=8 mips=4 dxgifmt=78 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5623 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5625 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5627 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5629 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5631 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5633 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5635 width=8 height=8 mips=4 dxgifmt=71 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5637 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5639 width=8 height=8 mips=4 dxgifmt=72 [D3D error was 887a0005]
d3d11: failed to create 2D texture id=5641 width=8 height=8 mips=4 dxgifmt=77 [D3D error was 887a0005]

**Comment by cheese3660** [comment]
Likely related to the LagRemover project, rather than space warp itself
